pub mod auth;
pub mod backup;
pub mod btree;
pub mod catalog;
pub mod engine;
pub mod error;
pub mod exec;
pub mod functions;
pub mod http;
pub mod migration;
pub mod plan;
pub mod repl;
pub mod server;
pub mod sql;
pub mod storage;
pub mod types;
pub mod webhooks;

pub use auth::{ExecutionContext, SessionClaims};
pub use backup::{dump_database, restore_database};
pub use engine::{Database, ExecResult, SharedDatabase};
pub use error::{DbError, Result};
pub use functions::{FunctionMetadata, FunctionRegistry};
pub use http::HttpServer;
pub use migration::{AppliedMigration, Migration, MigrationRunner};
pub use server::{Server, ServerConfig};
pub use types::value::Value;
pub use webhooks::{WebhookConfig, WebhookManager};
